// components/Navbar.vue
<script setup>
  const isMenuActive = ref(false);
  const toggleMenu = () => {
    isMenuActive.value = !isMenuActive.value;
  }
  defineProps({
    isHero: Boolean
  })
</script>

<template>
  <nav class="z-30 fixed top-0 flex items-center justify-between flex-row w-full h-14 backdrop-filter backdrop-blur-md bg-opacity-30" :class="isMenuActive ? '' : 'shadow'">
    <h1 class="font-bold text-2xl mx-4 text-blue-400">libyzxy0</h1>
    <ul class="flex justify-center md:justify-between items-center mx-4 hidden md:inline-flex w-auto flex-col md:flex-row" :class="isHero ? 'text-white' : 'text-gray-700'">
      <a href="#overview">
        <li class="md:0 text-xl font-medium transition-all duration-300 hover:text-blue-400 mx-3 hover:underline">Overview</li>
      </a>
      <a href="#about">
        <li class="text-xl font-medium transition-all duration-300 hover:text-blue-400 mx-3 hover:underline">About Me</li>
      </a>
      <a href="#projects">
        <li class="text-xl font-medium transition-all duration-300 hover:text-blue-400 mx-3 hover:underline">Projects</li>
      </a>
      <a href="#contact">
        <li class="text-xl font-medium transition-all duration-300 hover:text-blue-400 mx-3 hover:underline">Contact</li>
      </a>
    </ul>
    <button @click="toggleMenu" class="mx-4 border-none outline-none md:hidden" :class="isHero ? 'text-white' : 'text-gray-800'">
      <IconsBar v-if="!isMenuActive" />
      <IconsClose v-else />
    </button>
  </nav>
  <div class="z-20 fixed shadow-md h-auto w-full transition-all duration-300 backdrop-filter backdrop-blur-md bg-opacity-30" :class="isMenuActive ? 'top-14' : 'top-[-16rem]'">
    <ul class="flex justify-center items-center mx-4 w-auto flex-col py-4" :class="isHero ? 'text-white' : 'text-gray-700'">
      <a href="#overview">
        <li class="text-xl font-medium transition-all duration-300 hover:text-blue-400 py-1 hover:underline">Overview</li>
      </a>
      <a href="#about">
        <li class="text-xl font-medium transition-all duration-300 hover:text-blue-400 py-1 hover:underline">About Me</li>
      </a>
      <a href="#projects">
        <li class="text-xl font-medium transition-all duration-300 hover:text-blue-400 py-1 hover:underline">Projects</li>
      </a>
      <a href="#contact">
        <li class="text-xl font-medium transition-all duration-300 hover:text-blue-400 py-1 hover:underline">Contact</li>
      </a>
    </ul>
  </div>
</template>

// components/Navbar.tsx
"use client";

import { useEffect, useState } from "react";
import { ThemeToggle } from "@/components/ThemeToggle";
import Image from "next/image";
import logo from "@/assets/logo.png";
import { Menu, X } from "lucide-react";
import { Button } from "./ui/button";

const links = [
    { label: "Home", href: "#" },
    { label: "About", href: "#" },
    { label: "Education", href: "#" },
    { label: "Skills", href: "#" },
    { label: "Projects", href: "#" },
    { label: "Contact", href: "#" },
];

export default function Navbar() {
    const [isOpen, setIsOpen] = useState(false);
    const [isScrolled, setIsScrolled] = useState(false);

    useEffect(() => {
        const handleScroll = () => {
            if (window.scrollY > 50) {
                setIsScrolled(true);
            } else {
                setIsScrolled(false);
            }
        };

        window.addEventListener("scroll", handleScroll);
        return () => window.removeEventListener("scroll", handleScroll);
    }, []);

    return (
        <nav
            className={`sticky top-0 z-50 w-full h-20 px-6 flex flex-row items-center justify-between md:px-16 transition-all duration-300 ${isScrolled
                    ? "bg-background/90 backdrop-blur-md border-b border-border shadow-sm"
                    : "bg-transparent border-b border-transparent"
                }`}
        >
            <div className="flex flex-row items-center gap-2">
                <Image src={logo} alt="logo" className="h-12 w-12" />
                <h1 className="scroll-m-20 text-primary text-xl font-extrabold font-mono tracking-tight text-balance">
                    libyzxy0
                </h1>
            </div>

            <div className="hidden md:block">
                <ul className="flex flex-row items-center gap-4">
                    {links.map((link) => (
                        <li
                            key={link.label}
                            className="font-mono text-sm hover:bg-foreground hover:text-background px-1 transition-colors"
                        >
                            <a href={link.href}>{link.label}</a>
                        </li>
                    ))}
                    <li className="ml-4 mr-2">
                        <ThemeToggle />
                    </li>
                </ul>
            </div>

            <div className="flex items-center gap-2 md:hidden">
                <ThemeToggle />
                <Button
                    size="icon"
                    onClick={() => setIsOpen(true)}
                    aria-label="Open menu"
                >
                    <Menu className="h-6 w-6" />
                </Button>
            </div>

            {isOpen && (
                <div className="fixed inset-0 z-[60] bg-background flex flex-col md:hidden">
                    <div className="w-full h-20 px-6 flex items-center justify-between">
                        <div className="flex flex-row items-center gap-2">
                            <Image src={logo} alt="logo" className="h-12 w-12" />
                            <h1 className="scroll-m-20 text-primary text-xl font-extrabold font-mono tracking-tight text-balance">
                                libyzxy0
                            </h1>
                        </div>
                         <div className="flex items-center gap-2 md:hidden">
                <ThemeToggle />
                <Button
                    size="icon"
                    onClick={() => setIsOpen(false)}
                    aria-label="Open menu"
                >
                    <X className="h-6 w-6" />
                </Button>
            </div>

                    </div>

                    <ul className="flex flex-col items-center justify-center gap-8 flex-1">
                        {links.map((link) => (
                            <li key={link.label} className="font-mono text-xl">
                                <a href={link.href} onClick={() => setIsOpen(false)}>
                                    {link.label}
                                </a>
                            </li>
                        ))}
                    </ul>
                </div>
            )}
        </nav>
    );
}
